### ISSUE TITLE
with conflicts: glyphs and fontmake pipeline kerning rules appear to be not compatible

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#83]
I took tests written by @twardoch for https://github.com/googlei18n/glyphsLib/issues/24 and ran through the pipeline to generate fonts. I took the test  AV\*.otf fonts created for https://github.com/googlei18n/glyphsLib/issues/24 and AV\*.otf fonts produced by pipeline and ran them through @brawer 's fontdiff (glyphs produced otf font as --before font [pinkish color on the image below] and pipeline produced otf font as --after font [greenish color on the image below]).

I was hoping fontdiff will produce all white lines indicating that the bitmaps are equal (and this would imply that glyphs and fontmake pipeline kerning rules are compatible). However, it is not the case.

AV1 test
pipeline produced the following warning:
WARNING: Duplicate kerning rules found for glyph pair "a, v" (('public.kern1.A', 'v', -100) and ('a', 'public.kern2.V', 100)), removing pair from latter rule
![av1-test](https://cloud.githubusercontent.com/assets/13322623/15452643/3e41b21a-1fac-11e6-8929-b28607ef6137.jpg)

AV2 test
pipeline produced the following warnings:
WARNING: Duplicate kerning rules found for glyph pair "A, v" (('public.kern1.A', 'v', -100) and ('A', 'public.kern2.V', -400)), removing pair from latter rule
WARNING: Duplicate kerning rules found for glyph pair "a, v" (('public.kern1.A', 'v', -100) and ('a', 'public.kern2.V', 100)), removing pair from latter rule
![av2-test](https://cloud.githubusercontent.com/assets/13322623/15452644/45604d90-1fac-11e6-81e0-36280c2c9ed8.jpg)

AV3 test
pipeline produced the following warnings:
WARNING: Duplicate kerning rules found for glyph pair "a, V" (('public.kern1.A', 'V', -400) and ('a', 'public.kern2.V', 100)), removing pair from latter rule
WARNING: Duplicate kerning rules found for glyph pair "a, v" (('public.kern1.A', 'v', -100) and ('a', 'public.kern2.V', 100)), removing pair from latter rule
![av3-test](https://cloud.githubusercontent.com/assets/13322623/15452645/4c682aae-1fac-11e6-888a-c080e6d5408a.jpg)

All the files that were relevant to this test.

[Glyphs-AV-kerningTest.zip](https://github.com/googlei18n/fontmake/files/276206/Glyphs-AV-kerningTest.zip)

Sample fontdiff (actually using the old name ttfdiff) invocation

build/out/Default/ttfdiff \
  --before /Users/mrk/Downloads/Glyphs-AV-kerningTest/AV1-Regular.otf \
  --after /Users/mrk/Downloads/Glyphs-AV-kerningTest/pipeline/AV1-Regular.otf \
  --specimen specimen/AV-test.html \
  --out specimen/AV1-test.pdf

**Comment by brawer** [comment]
Context for those not working at Google: fontdiff is a font diffing tool that renders sample texts with HarfBuzz and FreeType into high-resolution bitmaps, using two versions of the same font. For each line of sample text, the look looks for visual differences between the renderings, and then it emits a PDF where the deltas are highlighted in color. At Google, we found this tool useful for checking the visual impact when we update a font’s source to a new version, and also when we re-build the exact same font sources with a new version of our font production pipeline. Eventually, we plan releasing the source code of this tool under the Apache 2.0 license, but the various legal reviews are still in progress so I cannot promise a specific date.

**Comment by marekjez86** [comment]
Since there was a release of Glyphs after the original sample was generated. I believe I received Version 2.3 (895) just recently, I exported otf files using the newest version and compared them to the version of otf posted as a sample to https://github.com/googlei18n/glyphsLib/issues/24 .  

There were no differences:
[AV1-test-glyphs-23895.pdf](https://github.com/googlei18n/fontmake/files/276372/AV1-test-glyphs-23895.pdf)
[AV2-test-glyphs-23895.pdf](https://github.com/googlei18n/fontmake/files/276371/AV2-test-glyphs-23895.pdf)
[AV3-test-glyphs-23895.pdf](https://github.com/googlei18n/fontmake/files/276370/AV3-test-glyphs-23895.pdf)

**Comment by marekjez86** [comment]
BTW, looks to me that for pipeline the opposite strategy would for the samples above: 

i.e.
instead of
WARNING: Duplicate kerning rules found for glyph pair "a, v" (('public.kern1.A', 'v', -100) and ('a', 'public.kern2.V', 100)), *removing pair from latter rule*
we should use the following
WARNING: Duplicate kerning rules found for glyph pair "a, v" (('public.kern1.A', 'v', -100) and ('a', 'public.kern2.V', 100)), *removing pair from the first rule*

and I think this would make the pipeline compatible with the Glyphs.app

**Comment by twardoch** [comment]
Yes, my understanding is that for duplicate pairs, Glyphs eliminates all except the last one.

**Comment by behdad** [comment]
Agree we should match what Glyphs does.

**Comment by brawer** [comment]
The fontdiff tool (which @marekjez86 used to find the issues on this bug) is now public:
https://github.com/googlei18n/fontdiff

**Comment by behdad** [comment]
Is this fixed now?

**Comment by marekjez86** [comment]
when I build the pipeline from recent noto-source I still have this problem so IMHO (it is not fixed yet)

**Comment by jamesgk** [comment]
Sorry, never updated requirement in fontmake. Should be fixed now.

**Comment by marekjez86** [comment]
At this point fontdiff displays no differences between the rendering of AV1-AV3 tests using fonts produced by the fontmake pipeline and the Glyphs.app. Below is the fontdiff output for AV1

![av1-result](https://cloud.githubusercontent.com/assets/13322623/15749126/32153712-2896-11e6-85b5-9e1ffb308868.jpg)

This bug fix is verified.

**Comment by behdad** [comment]
We should add this font to fontmake as an end-to-end test-suite.
